### ISSUE TITLE
CHANGELOG required setting inhibits bridge PRs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-onelogin#170]
### What happened?

https://github.com/pulumi/pulumi-onelogin/pull/169 for example. Looks like bridge update PRs will fail checks and won't automerge because of this setting.

### Example

See above

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I believe this is fixed in https://github.com/pulumi/pulumi-onelogin/pull/171
