### ISSUE TITLE
npm install @pulumi/onelogin throws error: @pulumi/onelogin is not found in this registry.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-onelogin#205]
### What happened?

Ran `npm i @pulumi/onelogin` and received this error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pulumi%2fonelogin - Not found
npm ERR! 404 
npm ERR! 404  '@pulumi/onelogin@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Attempts to install a specific version also threw not-found errors.

### Example

Run `npm i @pulumi/onelogin`

### Output of `pulumi about`

CLI          
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.5
Arch     x86_64

This project is written in nodejs: executable='/Users/mitch/.nvm/versions/node/v18.18.2/bin/node' version='v18.18.2'

Current Stack: pequod/onelogin-access/demo-mgmt

Found no resources associated with pequod/demo-mgmt

Found no pending operations associated with pequod/demo-mgmt

Backend        
Name           pulumi.com

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.100.0
@types/node     18.19.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by MitchellGerdisch** [comment]
FYI, Python install works.

**Comment by iwahbe** [comment]
I just triggered a patch release, which seemed to work. I am unable to see the created package in [npmjs.com](https://npmjs.com).

**Comment by iwahbe** [comment]
`@pulumi/onelogin` was marked as private. It should now be visible.
