### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-onelogin#39]
### What happened?

Main branch checks failing lint after last commit as noted in #team-provider-alerts channel

### Expected Behavior

NA

### Steps to reproduce

NA

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mnlumi** [comment]
CI no longer failing
